### PR TITLE
Add `ODOO_DATA_PATH` env var

### PR DESCRIPTION
**Pull request by simahawk**
Companion PR https://github.com/camptocamp/anthem/pull/36

### CODE REVIEW

**Comment by guewen** [comment]
@simahawk could you pin anthem with the new version 0.12.0?

FYI I'm trying to fix the gpg error in #46 at https://github.com/camptocamp/docker-odoo-project/pull/46/commits/8b905282435f1f11165f4553a85b79ae4d44231f

**Comment by simahawk** [comment]
@guewen done for all versions

**Comment by guewen** [comment]
Could you rebase?

**Comment by simahawk** [comment]
done

**Pull request merged**
