### PR TITLE
Misc build fixes

### PR DESCRIPTION
**Pull request by JGodin-C2C**

### CODE REVIEW

**Comment by simahawk** [comment]
@JGodin-C2C can you check the builds? Both PRs are red

**Comment by JGodin-C2C** [comment]
The builds are still red, but it looks like it is related to python PIP.
Should i try to fix this ? Or you prefer to dig into that ? 
It looks like a probleme in the setup.py ? 
Regards. 
J

**Comment by JGodin-C2C** [comment]
Got the bug . 
fix is on its way

**Comment by simahawk** [comment]
@leemannd would be better to fix the build 1st

**Comment by leemannd** [comment]
At least it's a partial fix.
As you wish.

**Comment by simahawk** [comment]
:fireworks: :tada:  thanks @JGodin-C2C it's all green now (even if does not appear here yet)!

**Comment by guewen** [comment]
Do you know why we never needed the reportlab fonts before and we don't need them on our local containers but need them for a particular customer?

**Pull request merged**
