### PR TITLE
Add 'unaccent' support

### PR DESCRIPTION
**Pull request by damdam-s**

### CODE REVIEW

**Comment by simahawk** [comment]
I don't see the pg contribs been installed. Aren't they needed for this feature to work?

**Comment by damdam-s** [comment]
@simahawk I don't know if this is managed in the docker postgresql image. If the extension is available, this should work.
I'm trying to test it locally

**Comment by guewen** [comment]
It's good to have in any case here, the postgres contrib is part of another container or setup.

**Comment by simahawk** [comment]
hmm, then would be nice to have a comment saying "hey, dude, you need to install this and this or use another image to use this",  no?

**Comment by guewen** [comment]
why not, the point is we don't have a "standard" postgres image, so the doc mostly refers to odoo's documentation, but it wouldn't hurt to add a link to the odoo documentation explaining the requirements

**Pull request merged**
