### PR TITLE
Fix missing .coveragerc for v11-12-13

### PR DESCRIPTION
**Pull request by simahawk**
Not sure if we should remove the lines (or update them) for v < 11

### CODE REVIEW

**Comment by guewen** [comment]
Shouldn't it be in Dockerfile-batteries too?

**Comment by simahawk** [comment]
> Shouldn't it be in Dockerfile-batteries too?

I thought so, @p-tombez told me it shouldn't be necessary (for us at least).

**Comment by p-tombez** [comment]
@guewen I thought Dockerfile-batteries was added on top of the other Dockerfile. If not, then the change need to be done in both files.

**Comment by simahawk** [comment]
done

**Comment by simahawk** [comment]
@guewen @p-tombez good for you?

**Comment by simahawk** [comment]
@p-tombez I've rebased. Would you mind review + merge to include this in next release? :pray:

**Pull request merged**
