### PR TITLE
Use debian stretch as base OS

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by yvaucher** [comment]
Restarting travis job as we had bunch of :
503  Service Temporarily Unavailable

**Comment by guewen** [comment]
we have issues with the wkhtmltopdf which is packaged only for jessie by odoo

**Comment by yvaucher** [comment]
https://github.com/odoo/odoo/issues/15308#issuecomment-276934340

According to sle-odoo only Wheezy and Jessie are supported for Odoo 10.0

Thus I guess we better wait for version 11.0 before we change this.

**Comment by guewen** [comment]
interesting, thanks for the info

**Comment by guewen** [comment]
Done in 2.5.0 with 11.0 support.

**Pull request closed without merging**
