### PR TITLE
Wkhtmltopdf 0.12.5.1

### PR DESCRIPTION
**Pull request by damdam-s**
superseeds #59

### CODE REVIEW

**Comment by yvaucher** [comment]
For the first travis job error this might help: #64

**Comment by guewen** [comment]
I read at several places than upgrading wkhtmltopdf changed the layout of many reports, we may want to be extra-cautious then

**Comment by leemannd** [comment]
@damdam-s Is it still needed?

**Comment by damdam-s** [comment]
@leemannd I have this in prod for a customer and seems to work pretty good. I don't know if we want this version of wkhtmltopdf in the base image.
@guewen opinion?

**Comment by guewen** [comment]
> @guewen opinion?

Do you know if the printed invoices did changed? I read in many places that the scale changed a bit in this version and some reports would then be offset

**Comment by damdam-s** [comment]
i'm not informed by the customer of any bug or layout issue on other reports

**Comment by guewen** [comment]
Oh, it seems the issues I mentioned are being fixed here https://github.com/odoo/odoo/pull/28864

**Comment by beledouxdenis** [comment]
@guewen 
I am glad my pull request can help you out :). It was becoming a technical debt for us as well to be stuck to wkhtmltopdf 0.12.1.

@damdam-s 
Up to now, using wkhtmltopdf 0.12.5 instead of 0.12.1 did render the reports with a different zoom level. Meaning, if you print the same report in Odoo (10.0/11.0/12.0) with 0.12.1 and 0.12.5 (even 0.12.2) you will see a difference in the zoom level.

My pull requests, which is being merged by our merge bot at the time I write this comment, aims to bring the compatibility so the zoom level remains exactly the same. I spent hours to find the trick.

That being said, for your customer, as you used 0.12.5 before we claimed it as officially supported, if you update the source code so it includes this compatibility revision, the reports of your customer will have a different zoom level, obviously, as it will now apply a zoom in (96/90 = 1.066667). If you want to keep your former zoom level, you can simply set "96" in your reports paper format: This will apply a zoom of 1.0, in other words no zoom.

**Comment by guewen** [comment]
@beledouxdenis Thanks a lot for the heads-up here, and congrats for finding the trick :hugs:

**Comment by yvaucher** [comment]
@damdam-s can you rebase / add an entry in changelog and apply the same change to version 12.0 ?

**Comment by guewen** [comment]
As we need a patch / recent revision on Odoo, should we always use the new version on 9.0/10.0/11.0?

**Comment by bealdav** [comment]
Hi,

As seen in #115 we have a real bug with 0.12.4 for v12 in one report.
No bug with runbot odoo v12, as i suppose it use 0.12.5.1 as supported version like 0.12.1

I plan to make a script wkhtml_12_5.sh called only in v12 Dockerfile for now.

What do you think ?

**Comment by guewen** [comment]
> I plan to make a script wkhtml_12_5.sh called only in v12 Dockerfile for now.

Agree

**Comment by bealdav** [comment]
Done in #115 
Can be closed here

**Pull request closed without merging**
