### PR TITLE
WIP: OpenERP 6.1 support: back to the future!

### PR DESCRIPTION
**Pull request by rvalyi**
WORK IN PROGRESS

you can typically test it with:

```
docker run --name some-postgres -e POSTGRES_PASSWORD=odoo -e POSTGRES_USER=odoo -d postgres:9.6.1
docker run -v /root/aflex-tests/odoo:/opt/odoo -e MIGRATE=False -e ADDONS_PATH=/opt/odoo/src/addons --link some-postgres:db -ti camptocamp/odoo-project:6.1-latest openerp-server
```

### CODE REVIEW

**Comment by rvalyi** [comment]
note: with this PR and the new `bin/docker-entrypoint_6.1.sh` entry point we typically only start the main process but not Gunicorn. Both processes would typically be started with supervisor. However, in our project we used Ruby Bluepill because it seems it was easier for us to properly supervise the memory usage of the broken libreoffice we used for Aeroo reports (I'll eventually point to the proper Akretion branch later). But all I mean is that supervisor support was out of scope of this simple PR.

**Comment by yvaucher** [comment]
@rvalyi do you still have interest in this?

**Comment by gurneyalex** [comment]
I'm :-1: on maintaining python2 support on this project.

**Comment by rvalyi** [comment]
Hello, no more interest for this PR on my side.
About more recent Python 2.7 containers: we have some interest to migrate a few V8 customers, so for v9 and v10 (possibly just this year). But we will do it our way, I understand you deprecate theses versions.

**Comment by gurneyalex** [comment]
FTR we are in the progress of a major change to stop running as root, and we will likely drop support for python2 in the process.

**Pull request closed without merging**
